### ISSUE TITLE
Not install cine

### ISSUE THREAD

**Issue by d3n-nc** [CineDeveloper/cineAndFei-installer#1]
[admin@ns cine]$ sudo ./install.sh 
Installing ...
/bin/ld: cannot find crtbegin.o: No such file or directory
/bin/ld: cannot find -lgcc
/bin/ld: cannot find -lgcc_s
clang: error: linker command failed with exit code 1 (use -v to see invocation)
After compilation, an executable file was not found.(/usr/bin/cine)/bin/ld: cannot find crtbegin.o: No such file or directory
/bin/ld: cannot find -lgcc
/bin/ld: cannot find -lgcc_s
clang: error: linker command failed with exit code 1 (use -v to see invocation)
After compilation, an executable file was not found.(/usr/bin/fei)Done.

**Comment by d3n-nc** [comment]
yum -y install make cmake clang gcc cpp

**Comment by CineDeveloper** [comment]
> yum -y install make cmake clang gcc cpp

Did this help you or was it installed?

**Comment by d3n-nc** [comment]
I not install gcc. This decision helped. Closed issue.
